[package]
name = "word_iter"
version = "0.2.0"
authors = ["Nils Martel <nilsmartel@yahoo.de>"]
edition = "2018"
repository = "https://github.com/nilsmartel/words"
description = "Simple Iterator over all words in a string"
license = "MIT"

[dependencies]
